# Generated by Django 4.2.17 on 2024-12-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0003_alter_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
